# Docker Compose configuration for Rails Survey Form Application

services:
  # Rails application
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=sqlite3:/app/db/development.sqlite3
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    depends_on:
      - db
    command: bundle exec rails server -b 0.0.0.0 -p 3000

  # Database service (SQLite for simplicity, but you can use PostgreSQL)
  db:
    image: alpine:latest
    volumes:
      - sqlite_data:/app/db
    command: sh -c "apk add --no-cache sqlite && mkdir -p /app/db && touch /app/db/development.sqlite3 && tail -f /dev/null"

  # Redis (optional, for caching)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  bundle_cache:
  sqlite_data:
  redis_data: 